# Generated by Django 5.1.4 on 2025-01-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_musicprofile_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem2',
            new_name='TodoItem3',
        ),
    ]
