# Generated by Django 5.1.4 on 2025-01-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_rename_todoitem2_todoitem3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoItem3',
            new_name='TodoItem2',
        ),
    ]
