# Generated by Django 5.1.4 on 2025-01-04 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_todoitem3_todoitem2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Seller',
        ),
    ]
