# Generated by Django 5.1.4 on 2025-01-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_remove_seller_year_in_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='year_in_university',
            field=models.CharField(choices=[('1 курс', '1'), ('2 курс', '2'), ('3 курс', '3'), ('4 курс', '4'), ('5 курс', '5')], default='1 курс', max_length=6),
        ),
    ]
