# Generated by Django 5.1.4 on 2025-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_alter_seller_year_in_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='year_in_university',
            field=models.CharField(choices=[('1', '1 курс'), ('2', '2 курс'), ('3', '3 курс'), ('4', '4 курс'), ('5', '5 курс')], default='1', max_length=1),
        ),
    ]
